### ISSUE TITLE
Add life highlights as JSON

### ISSUE THREAD

**Issue by ronilaukkarinen** [afonsocrg/mementoMori#5]
Certain life events like birthdays, moving, death of a close one, turning 30 etc. would be a blast to add to the blocks with different colors/styles. You'd see the occasion as tooltip or something when hovering the block. It would be perfect to be able to add your own data as json like in [entire.life](https://entire.life/) or [life calendar](https://github.com/ngduc/life-calendar) (I like the idea of these two but I'd like to own my data instead).

The JS side is not my strongest suit but I'm glad to help with the styles.

**Comment by afonsocrg** [comment]
I also love this idea, both the tooltip and the different colors.

This also begs for an interface where we can manage those events and configure them (change color, description, date, etc).

Once again, I'm not that good with CSS, so if you could PR some static example (maybe in another file), that would be awesome!!

**Comment by ronilaukkarinen** [comment]
> Once again, I'm not that good with CSS, so if you could PR some static example (maybe in another file), that would be awesome!!

I will in near future. Tooltips need a bit work but it's rather easy to do for me. I'll let to you know in a form of PR as soon as it's ready.

**Comment by afonsocrg** [comment]
Thanks a lot!!
